<a href="https://colab.research.google.com/github/tahminahasan/ML-Notebook/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#dimension
a.ndim

2

In [4]:
#bytes
a.itemsize


8

In [5]:
#row column
a.shape

(3, 3)

In [6]:
b=np.array([[1,2,3],[4,7,8],[8,9,11]],dtype =np.float64)
print (b)

[[ 1.  2.  3.]
 [ 4.  7.  8.]
 [ 8.  9. 11.]]


In [7]:
#array fillers
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
a=np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a=np.full((3,3),10)
a

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [10]:
a=np.empty((3,3))
a

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  8.],
       [ 8.,  9., 11.]])

In [11]:
#returns evenly spaced values over a specified range
c = np.linspace(1,5,50)
c

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [12]:
#generates an array starting from start and stops before stop
x=np.arange(1,12)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
#change the shape or dimensions without changing data.
p=np.array([[1,2,3], [4,5,6]])
p.reshape (3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
#math operation
a=np.arange(0,24). reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
a.max()

23

In [16]:
#calculates the sum along columns (vertically)
a.sum(axis=0)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])

In [17]:
#sums along rows (horizontally)
a.sum (axis=1)

array([ 66, 210])

In [18]:
np.sqrt (a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
        3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563, 4.24264069, 4.35889894, 4.47213595, 4.58257569,
        4.69041576, 4.79583152]])

In [19]:
#slicing
b=np.arange(0,30). reshape(3,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
#b[0:2] selects the first two rows of the array b
b[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
#first two rows
b[0:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [22]:
#first two columns
b[:,0:2]

array([[ 0,  1],
       [10, 11],
       [20, 21]])

In [24]:
#sub matrix, rows(index 0 and 1) and col(index 5-7 )
b[0:2, 5:8]

array([[ 5,  6,  7],
       [15, 16, 17]])

In [25]:
#step zip, : → Selects all rows, ::step → Selects columns with a step size of step
#b [:,::3] >>: selects all rows, ::3 selects every third columns
b[:,::3]

array([[ 0,  3,  6,  9],
       [10, 13, 16, 19],
       [20, 23, 26, 29]])

In [27]:
t=b[2,7]
t

27

In [28]:
a=np.arange(6,12).reshape(3,2)
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
#loop . C is C-style row-major order
for x in np.nditer(a, order = 'C'):
  print (x)

6
7
8
9
10
11


In [30]:
#1d
for x in np.nditer(a, order = 'K', flags = ['external_loop']):
  print (x)

[ 6  7  8  9 10 11]


In [31]:
for x in np.nditer(a, order = 'K', op_flags = ['readwrite']):
  x[...]=x*x
  print (x)

36
49
64
81
100
121


In [32]:
a=np.arange(6,12).reshape(3,2)
b=np.arange(0,6).reshape(3,2)


In [33]:
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
#merge
for x, y in np.nditer([a,b]):
  print (x,y)

6 0
7 1
8 2
9 3
10 4
11 5


In [36]:
#loop
for row in a:
  print (row)

[6 7]
[8 9]
[10 11]


In [37]:
#loop 1D
for row in a.flat:
  print (row)

6
7
8
9
10
11


In [38]:
a=np.arange(0,12).reshape(3,4)
b=np.arange(12,24).reshape(3,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a+b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [41]:
a*b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [42]:
#vertical stack
c=np.vstack((a,b))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
#horizontal stack
c=np.hstack((a,b))
c

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [45]:
a=np.arange(0,50).reshape(5,10)
a


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
result = np.hsplit(a,2)

In [47]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [48]:
result [1]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [49]:
a=np.arange(0,60).reshape(6,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [50]:
b=(a>20)
b

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [52]:
#replace value
a[b]=-1
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])